version: '3.8'

services:
  api:
    build: .
    container_name: app_baby_routine
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      # Modificado para bind mount: facilita colocar o backup (baby_routine.db) na pasta ./data
      - ./data:/app/data
    restart: always
    
  docs:
    image: node:lts
    container_name: docs_baby_routine
    working_dir: /app/docs
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm start -- --host 0.0.0.0
    restart: always

# Removido o block volumes: baby_data: pois agora usamos bind mount ./data
