version: '3.8'

services:
  api:
    build: .
    container_name: app_baby_routine
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      # Isso cria um volume gerenciado pelo Docker que guarda os dados do SQLite com segurança
      - baby_data:/app/data
    restart: always

volumes:
  baby_data:
